# Generated by Django 4.2.4 on 2023-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='numero_identificacion',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
