# Generated by Django 4.2.4 on 2023-11-03 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cuenta_numero_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'documento_clase',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fechaRegistro', models.DateTimeField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cuenta')),
                ('documento_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.documentoclase')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
    ]
