# Generated by Django 4.2.4 on 2023-11-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_documentoclase_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoclase',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
